### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by john-french** [gmit-sweng-20/ca5-bdd-tdd-cycle-Ultan-Kearns#6]
@Ultan-Kearns 
- This isn't testing the controller. Not really sure what it's testing.
https://github.com/gmit-sweng-20/ca5-bdd-tdd-cycle-Ultan-Kearns/blob/5b834e01815016aa18e23ed6229892066cfc0e13/rottenpotatoes/spec/controllers/movies_controller_spec.rb#L37
- Similar issue with the model tests, they're not testing anything
https://github.com/gmit-sweng-20/ca5-bdd-tdd-cycle-Ultan-Kearns/blob/5b834e01815016aa18e23ed6229892066cfc0e13/rottenpotatoes/spec/models/movie_spec.rb#L6
- Not checking anything here, so it's not a test
https://github.com/gmit-sweng-20/ca5-bdd-tdd-cycle-Ultan-Kearns/blob/5b834e01815016aa18e23ed6229892066cfc0e13/rottenpotatoes/spec/controllers/movies_controller_spec.rb#L17
- Delete test makes sense

Some misunderstanding here about how tests should be written I think, otherwise good effort.

Please close this issue to acknowledge receipt of feedback.

**Comment by Ultan-Kearns** [comment]
Thanks for the feedback John
